server:
  port: 0
  servlet:
    context-path: /map
  message:
    basename: messages
  forward-headers-strategy: framework
#  port: ${random.int(10000,51000)}

spring:
  application:
    name: mapservice-rest
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://118.67.132.31:5432/map-service
    username: admin
    password: xogml159
  # 동적이지않아 코드로 변경
  #security:
  #  user:
  #    name: stylealist
  #    password: 1q2w3e4r
    #platform: postgres

logging:
  level:
    org.springframework: debug
# 추후 보안에 맞게 설정해야 함
management:
  endpoints:
    web:
      exposure:
        include: "self,health"
