# test
# application.yml
server:
  port: 0
  servlet:
    context-path: /map
  message:
    basename: messages
  forward-headers-strategy: framework
#  port: ${random.int(10000,51000)}

spring:
  application:
    name: mapservice-rest
  datasource:
    url: jdbc:postgresql://211.188.62.54:30017/sjlab
    username: stylealist
    password: "!@xogml159"
    driver-class-name: org.postgresql.Driver  # URL로 자동판별되지만 명시해도 OK

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  #profiles:
  #  active: local
  #datasource:
  #  url: jdbc:postgresql://118.67.132.31:5432/map-service
  #  username: admin
  #  password: xogml159
  #jpa:
  #  hibernate:
  #    ddl-auto: update
  #  properties:
  #    hibernate:
  #      format_sql: true
  #  show-sql: true

logging:
  level:
    org.springframework: info
    root: info
# 추후 보안에 맞게 설정해야 함
management:
  endpoints:
    web:
      exposure:
        include: "self,health"

# 동적이지않아 코드로 변경
#security:
#  user:
#    name: stylealist
#    password: 1q2w3e4r
#platform: postgres