#spring:
#  data:
#    rest:
#      base-path: /api/map
    #platform: postgres

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://www.sj-lab.co.kr/discovery/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: /api/map/v3/api-docs/swagger-config # NOTE: API GW 에서 접근 가능하게 하기 위해 /{apiGwStageName}/{prefixPath} 를 붙여줌
    url: /api/map/v3/api-docs