server:
  port: 0
  servlet:
    context-path: /map
#  port: ${random.int(10000,51000)}

spring:
  application:
    name: mapservice-rest
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://118.67.132.31:5432/postgres
    username: admin
    password: xogml159
    #platform: postgres
